# I've removed most of the lines from the template config generated via
# cargo deny init to keep this readable.
# If you want to change something it may be worthwhile to run cargo deny init
# to get an overview of the options and their defaults.

# Note that all fields that take a lint level have these possible values:
# * deny - An error will be produced and the check will fail
# * warn - A warning will be produced, but the check will not fail
# * allow - No warning or error will be produced, though in some cases a note
# will be

[advisories]
version = 2
ignore = [
   "RUSTSEC-2020-0056",
   "RUSTSEC-2020-0077",
   "RUSTSEC-2021-0059",
   "RUSTSEC-2021-0060",
   "RUSTSEC-2021-0064",
   "RUSTSEC-2023-0086",
   "RUSTSEC-2024-0384",
]

[bans]
multiple-versions = "allow"

[licenses]
version = 2
confidence-threshold = 0.8

allow = [
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "CC0-1.0",
    "GPL-2.0",
    "LGPL-2.1 WITH GCC-exception-2.0",
    "MIT",
    "Unicode-3.0",
    "Unicode-DFS-2016",
    "Unlicense",
    "WTFPL",
    "Zlib",
]
